// <auto-generated />
using System;
using AirBB.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBBContext))]
    [Migration("20251130042425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AirBB.Models.DomainModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            DOB = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "owner@example.com",
                            Name = "John Owner",
                            PhoneNumber = "1111111111",
                            SSN = "000000000",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Boston",
                            Name = "Boston"
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Chicago",
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 3,
                            City = "New York",
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accommodation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BathroomNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bathrooms")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ResidencePicture")
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 101,
                            Accommodation = 4,
                            BathroomNumber = 1.0m,
                            Bathrooms = 1.0m,
                            BedroomNumber = 2,
                            Bedrooms = 2,
                            BuiltYear = 2005,
                            GuestNumber = 4,
                            Image = "boston.jpg",
                            LocationId = 1,
                            Name = "Boston Back Bay Condo",
                            OwnerId = 1,
                            Price = 179m,
                            PricePerNight = 179m,
                            ResidencePicture = "boston.jpg"
                        },
                        new
                        {
                            ResidenceId = 102,
                            Accommodation = 3,
                            BathroomNumber = 1.0m,
                            Bathrooms = 1.0m,
                            BedroomNumber = 1,
                            Bedrooms = 1,
                            BuiltYear = 2010,
                            GuestNumber = 3,
                            Image = "chicago.jpg",
                            LocationId = 2,
                            Name = "Chicago Loop Apartment",
                            OwnerId = 1,
                            Price = 129m,
                            PricePerNight = 129m,
                            ResidencePicture = "chicago.jpg"
                        },
                        new
                        {
                            ResidenceId = 103,
                            Accommodation = 2,
                            BathroomNumber = 1.0m,
                            Bathrooms = 1.0m,
                            BedroomNumber = 1,
                            Bedrooms = 1,
                            BuiltYear = 2015,
                            GuestNumber = 2,
                            Image = "nyc.jpg",
                            LocationId = 3,
                            Name = "NYC Midtown Studio",
                            OwnerId = 1,
                            Price = 149m,
                            PricePerNight = 149m,
                            ResidencePicture = "nyc.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Experience", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Category", "Category")
                        .WithMany("Experiences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Residence", "Residence")
                        .WithMany("Reservations")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBB.Models.DomainModels.Client", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Category", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Navigation("Residences");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
